version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1
  node: circleci/node@4.7.0
workflows:
  elastic-beanstalk-workflow:
    jobs:
      - eb/deploy:
          app-dir: ~/project/backend
          context: aws-creds
          application-name: Application AT-Preparing-an-Application-for-Deployment
          environment-name: AT-Preparing-an-Application-for--env
          filters:
            branches:
              only:
                - main
          label: version-<<pipeline.number>>
        
